### ISSUE TITLE
Mails sent by Thunderbird have clipped bodies

### ISSUE THREAD

**Issue by haelge** [dschmidt/billo#5]
**Summary:**
Mails sent by thunderbird are missing the first line of text in the body.

**Steps to Reproduce:**
Write and send a mail to the imap inbox of a billo list using thunderbird (68.8.0 (64-bit))

**Expected Results:**
The complete message should be delivered to the list member

**Actual Results:**
The delivered mail is missing the first line of text. (In thunderbird as well as webmail e.g.)

**Comment by haelge** [comment]
BUT in the imap mailbox itself the message is complete, weird I look further into it.

**Comment by dschmidt** [comment]
That's pretty interesting.
Exactly one line missing sounds as if it was caused by this code:
https://github.com/dschmidt/billo/blob/c5477a6c5a07a4b8a3830212f6963bf6dad19fc0/src/billo.php#L38

It strips the first line of the body. I did it because in my tests `$content` always contained a first line like: `This is a multi-part message in MIME format.` which seemed to break stuff at the time. Maybe I only added the right content type afterwards, so stripping that line in fact wasn't neccessary or rather plain wrong.

**Comment by dschmidt** [comment]
Okay, I removed the stripping of that line - and everything looks fine still. 
I'm just surprised this was never an issue for me - maybe my Thunderbird always sent mime messages?!

I'll push the change and you can test again...

**Comment by haelge** [comment]
Man I'm blind. You don't want to know how deep i got into RFC 821 examining the importance of correct TransferEncodings and how Thunderbird does it.

**Comment by dschmidt** [comment]
Pushed, can you confirm this fixes the issue for you? 

P.S.: :hugs:

**Comment by haelge** [comment]
It does, but there is still a thing with Transfer-Encoding going on. But for now this seems to be a problem on the webmailers side. You can close this issue.

**Comment by dschmidt** [comment]
If you can figure out what's going on, we can work on a fix together.
Feel free to open a new issue to discuss :)
